services:
- mongodb

language: node_js
node_js:
    - "4"
    - "6"
before_script:
    - npm install
    - npm install istanbul -g
script:
- npm test
after_script:
- npm run coveralls

notifications:
  email:
     - isnack.yagami@gmail.com